package model;

public enum ErrorType {
    SUCCESS,
    NOT_A_WORD,
    OUT_OF_BOUNDS,
    DID_NOT_USE_EXISTING_LETTERS,
    OVERRODE_EXISTING_LETTERS,
    DO_NOT_HAVE_LETTERS,
    NOT_IN_CENTER,
    BAD_LOCATION,
    NOT_YOUR_TURN,
    LAST
}
